# See https://docs.godotengine.org/en/stable/contributing/development/compiling/optimizing_for_size.html for optimize flag lists.
# See https://docs.godotengine.org/en/stable/contributing/development/compiling/introduction_to_the_buildsystem.html#overriding-the-build-options for more info on how to use this file.

debug_symbols = "no"
lto = "full"
optimize = "size"

# Disable this to use Advanced Godot's text server. See: https://docs.godotengine.org/en/stable/contributing/development/compiling/optimizing_for_size.html#disabling-advanced-text-server
module_text_server_adv_enabled = "no"
module_text_server_fb_enabled = "yes"

disable_3d = "yes"

module_basis_universal_enabled = "no"
module_bmp_enabled = "no"
module_camera_enabled = "no"
module_csg_enabled = "no"
module_dds_enabled = "no"
module_enet_enabled = "no"
module_gridmap_enabled = "no"
module_hdr_enabled = "no"
module_jsonrpc_enabled = "yes"
module_ktx_enabled = "no"
module_mbedtls_enabled = "no"
module_meshoptimizer_enabled = "no"
module_minimp3_enabled = "no"
module_mobile_vr_enabled = "no"
module_msdfgen_enabled= "no"
module_multiplayer_enabled = "no"
module_noise_enabled = "no"
module_navigation_enabled = "no"
module_ogg_enabled = "no"
module_openxr_enabled = "no"
module_raycast_enabled = "no"
module_regex_enabled = "yes"
module_squish_enabled = "no"
module_svg_enabled = "yes"
module_tga_enabled = "no"
module_theora_enabled = "no"
module_tinyexr_enabled = "no"
module_upnp_enabled = "no"
module_vhacd_enabled = "no"
module_vorbis_enabled = "no"
module_webrtc_enabled = "no"
module_websocket_enabled = "no"
module_webxr_enabled = "no"
module_zip_enabled = "no"